[build-system]
requires = [
    "meson-python>=0.15.0",
    "numpy",
    "cython",
]
build-backend = "mesonpy"

[project]
name = "metro-eval"
version = "0.0.2"
authors = [
  {name = "Adrian Peter Krone", email= "adrian.krone@physik.uni-kassel.de"},
]
description = "Evaluation utilities for metro data"
readme = "README.rst"
license = "MPL-2.0"
license-files = ["LICENSE"]
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",
]
dependencies = [
    "h5py>=3.13.0",
    "numpy>=1.21",
    "pyqtgraph>=0.14.0",
    "pyside6>=6.10.2",
    "rich>=14.2.0",
]

[project.scripts]
metro-eval = "metro_eval.__main__:main"

[project.optional-dependencies]
dev = [
    "cython>=3.2.4",
    "meson-python>=0.19.0",
    "ninja>=1.13.0",
    "numpy>=2.4.2",
]
docs = [
    "jupyter>=1.1.1",
    "matplotlib>=3.10.8",
    "nbsphinx>=0.9.7",
    "numpydoc>=1.8.0",
    "pandoc>=2.4",
    "sphinx>=7.4.7",
    "sphinx-argparse>=0.4.0",
    "sphinx-autodoc-typehints>=2.3.0",
    "sphinx-copybutton>=0.5.2",
    "sphinx-rtd-theme>=3.0.2",
]
test = [
    "pytest>=9.0.3",
]

[project.urls]
GitHub = "https://github.com/exp4-age/metro-eval"

[tool.ruff]
line-length = 79

[tool.ruff.lint]
select = ["E", "E7", "E9", "F", "A", "B"]
