name: Test

on:
  pull_request:
    paths:
      - src/**
      - tests/**
      - pyproject.toml
      - .github/workflows/test.yml

jobs:
  test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            python-version: "3.14"
            pure-python: 1
          - os: windows-latest
            python-version: "3.14"
            pure-python: 0
          - os: ubuntu-latest
            python-version: "3.14"
            pure-python: 0
          - os: ubuntu-latest
            python-version: "3.13"
            pure-python: 0
          - os: ubuntu-latest
            python-version: "3.12"
            pure-python: 0
          - os: ubuntu-latest
            python-version: "3.11"
            pure-python: 0
      fail-fast: false

    steps:
    - uses: actions/checkout@v6
    - uses: astral-sh/setup-uv@v7
    - uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install package
      env:
        PURE_PYTHON: ${{ matrix.pure-python }}
      run: uv pip install --system . pytest
    - name: Run tests
      env:
        PURE_PYTHON: ${{ matrix.pure-python }}
      run: pytest
